{% set name = "biome" %}
{% set version = "1.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biomejs/{{ name }}/archive/refs/tags/cli/v{{ version }}.tar.gz
  sha256: fc06a89e1b925e8b1dfaca98f7af1d8e04d27acdcaeff786e2806f8bc26283f9

build:
  number: 1
  script_env:
    - BIOME_VERSION={{ version }}
    - RUSTFLAGS=-Cstrip=symbols
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --locked --root "$PREFIX" --path crates/biome_cli           # [unix]
    - cargo install --locked --root "%LIBRARY_PREFIX%" --path crates/biome_cli  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

test:
  commands:
    - biome --version

about:
  home: https://biomejs.dev
  doc_url: https://biomejs.dev/guides/getting-started/
  dev_url: https://github.com/biomejs/biome
  summary: |
    A toolchain for web projects, aimed to provide functionalities to maintain them.
    Biome offers formatter and linter, usable via CLI and LSP. 
  description: |
    Biome is a performant toolchain for web projects, it aims to provide developer tools to maintain the health of said projects.
    Biome is a fast formatter for JavaScript, TypeScript, JSX, and JSON that scores 97% compatibility with Prettier.
    Biome is a performant linter for JavaScript, TypeScript, and JSX that features more than 200 rules from ESLint, typescript-eslint, and other sources.
    It outputs detailed and contextualized diagnostics that help you to improve your code and become a better programmer!
    Biome is designed from the start to be used interactively within an editor.
    It can format and lint malformed code as you are writing it.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - AntoinePrv
