schema_version: 1

context:
  name: biome
  version: "2.3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/biomejs/${{ name }}/archive/refs/tags/@biomejs/biome@${{ version }}.tar.gz
  sha256: 0ba5afb0076bb267d2e734e158a613363b8eb238406fd8032444e549bcc1ea65

build:
  number: 1
  script:
    env:
      BIOME_VERSION: ${{ version }}
      # OSX would link with /usr/lib/libiconv.2.dylib
      RUSTFLAGS: >
        ${{
          "-C strip=symbols -C embed-bitcode=yes -C lto=thin"
          ~ (" -C link-arg=-Wl,-rpath,${PREFIX}/lib -L${PREFIX}/lib" if osx else "")
        }}
      # Reduce parallelism to reduce max memory
      CARGO_BUILD_JOBS: ${{ "1" if env.exists("CI") else "-1" }}
    content:
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
      - if: unix
        then:
          - cargo install --locked --root "$PREFIX" --path crates/biome_cli -v
        else:
          - cargo install --locked --root "%LIBRARY_PREFIX%" --path crates/biome_cli -v

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - cargo-bundle-licenses
  host:
    - if: osx
      then: libiconv

tests:
  - script:
      - biome --version

about:
  summary: |
    A toolchain for web projects, aimed to provide functionalities to maintain them.
    Biome offers formatter and linter, usable via CLI and LSP.
  description: |
    Biome is a performant toolchain for web projects, it aims to provide developer tools to maintain the health of said projects.
    Biome is a fast formatter for JavaScript, TypeScript, JSX, and JSON that scores 97% compatibility with Prettier.
    Biome is a performant linter for JavaScript, TypeScript, and JSX that features more than 200 rules from ESLint, typescript-eslint, and other sources.
    It outputs detailed and contextualized diagnostics that help you to improve your code and become a better programmer!
    Biome is designed from the start to be used interactively within an editor.
    It can format and lint malformed code as you are writing it.
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  homepage: https://biomejs.dev
  repository: https://github.com/biomejs/biome
  documentation: https://biomejs.dev/guides/getting-started/

extra:
  recipe-maintainers:
    - AntoinePrv
